version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: "rabbitmq"
    env_file:
      - .env.docker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
  control_plane:
    image: snowflake_cybersyn_demo:latest
    command: sh -c "python -m snowflake_cybersyn_demo.core_services.control_plane"
    env_file:
      - .env.docker
    ports:
      - "8001:8001"
    volumes:
      - ./snowflake_cybersyn_demo:/app/snowflake_cybersyn_demo # load local code change to container without the need of rebuild
      - ./logging.ini:/app/logging.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8001/ || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  funny_agent:
    image: snowflake_cybersyn_demo:latest
    command: sh -c "python -m snowflake_cybersyn_demo.agent_services.funny_agent"
    env_file:
      - .env.docker
    ports:
      - "8002:8002"
    volumes:
      - ./snowflake_cybersyn_demo:/app/snowflake_cybersyn_demo # load local code change to container without the need of rebuild
      - ./data:/app/data
      - ./logging.ini:/app/logging.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8002/is_worker_running || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  goods_getter_agent:
    image: snowflake_cybersyn_demo:latest
    command: sh -c "python -m snowflake_cybersyn_demo.agent_services.financial_and_economic_essentials.goods_getter_agent"
    env_file:
      - .env.docker
    ports:
      - "8003:8003"
    volumes:
      - ./snowflake_cybersyn_demo:/app/snowflake_cybersyn_demo # load local code change to container without the need of rebuild
      - ./data:/app/data
      - ./logging.ini:/app/logging.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8003/is_worker_running || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  time_series_getter_agent:
    image: snowflake_cybersyn_demo:latest
    command: sh -c "python -m snowflake_cybersyn_demo.agent_services.financial_and_economic_essentials.time_series_getter_agent"
    env_file:
      - .env.docker
    ports:
      - "8004:8004"
    volumes:
      - ./snowflake_cybersyn_demo:/app/snowflake_cybersyn_demo # load local code change to container without the need of rebuild
      - ./data:/app/data
      - ./logging.ini:/app/logging.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8004/is_worker_running || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  stats_getter_agent:
    image: snowflake_cybersyn_demo:latest
    command: sh -c "python -m snowflake_cybersyn_demo.agent_services.government_essentials.stats_getter_agent"
    env_file:
      - .env.docker
    ports:
      - "8005:8005"
    volumes:
      - ./snowflake_cybersyn_demo:/app/snowflake_cybersyn_demo # load local code change to container without the need of rebuild
      - ./data:/app/data
      - ./logging.ini:/app/logging.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8005/is_worker_running || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
volumes:
  rabbitmq:
secrets:
  id_ed25519:
    file: ~/.ssh/id_ed25519
